//
// Created by Andres on 22/04/2026.
//

#ifndef CLASE10_PUNTEROSAFUNCIONES_FUNCIONESDEENTERIS_H
#define CLASE10_PUNTEROSAFUNCIONES_FUNCIONESDEENTERIS_H

#endif //CLASE10_PUNTEROSAFUNCIONES_FUNCIONESDEENTERIS_H
